### ISSUE TITLE
Make available on Maven Central and/or jCenter

### ISSUE THREAD

**Issue by maurizi** [acebaggins/gson-serializers#1]
Nice looking project!

**Comment by acebaggins** [comment]
Thanks!
Sorry for the late reply, I was on vacation. I'll put it on Maven Central.

**Comment by vyshane** [comment]
I second this :)

**Comment by acebaggins** [comment]
Sorry, it should be (off the top of my head) apache

**Comment by vyshane** [comment]
Hi @acebaggins, did you mean to reply to #2?

**Comment by acebaggins** [comment]
Probably.

**Comment by vyshane** [comment]
Would you mind checking in a LICENSE file, just to make your choice of the Apache license official?

**Comment by robfletcher** [comment]
It would be great to have this available somewhere.

**Comment by MiWeiss** [comment]
@acebaggins I couldn't find it on maven central yet. Are you ok if I upload it for you? Or, If you have already uploaded it, would you mind putting linking it in the readme of this repository?

**Comment by acebaggins** [comment]
I would love to upload it but I'm (embarrassingly) unsure how to do that.

**Comment by MiWeiss** [comment]
Maybe this helps: 
http://central.sonatype.org/pages/ossrh-guide.html
Thanks in advance :-)

**Comment by islerfab** [comment]
@acebaggins Do you have any news on this? I would love to include your deserializers in a maven project. If you don't plan to put it on maven central, may I include your classes directly when I correctly reference this repo in the code?

**Comment by acebaggins** [comment]
I'm putting in the request but I'm a little worried about how poorly this project is named. Would you like me to change the group/artifact name or would that create too many problems?

**Comment by islerfab** [comment]
This wouldn't create any problem. However, since I had the need to go forward, I found a way to get around serializing the immutables. But since it may still be a need again in future and I see the interest of other people as well, it would still be great to find this on maven central! :thumbsup:

**Comment by acebaggins** [comment]
https://github.com/acebaggins/guava-gson-serializers/packages
